{
 "title": "Nolus Dashboard",
 "description": "A Grafana dashboard compatible with all the cosmos-sdk and tendermint based blockchains.",
 "tags": [
  "Blockchain",
  "Cosmos"
 ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": {
     "query": "label_values(tendermint_consensus_height, chain_id)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(tendermint_consensus_height{chain_id=\"$chain_id\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$chain_id overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "<img width=\"800px\" src=\"https://i.pinimg.com/originals/2c/15/a5/2c15a538a5fc305fe2d927a66854556b.jpg\" />"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_height{chain_id=\"$chain_id\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Bonded Tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power{chain_id=\"$chain_id\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_total_txs{chain_id=\"$chain_id\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Voting Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Online"
    },
    {
     "expr": "tendermint_consensus_missing_validators_power{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "tendermint_consensus_byzantine_validators_power{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_validators{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "tendermint_consensus_missing_validators{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "tendermint_consensus_byzantine_validators{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_num_txs{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Block Size"
    }
   ]
  },
  {
   "title": "instance overview: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tendermint_p2p_peers{chain_id=\"$chain_id\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Unconfirmed Transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tendermint_mempool_size{chain_id=\"$chain_id\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Failed Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_mempool_failed_txs{chain_id=\"$chain_id\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Recheck Times",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_mempool_recheck_times{chain_id=\"$chain_id\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Network Input",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "tendermint_p2p_peer_receive_bytes_total{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Total Network Output",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "tendermint_p2p_peer_send_bytes_total{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  }
 ]
}